[package]
name = "modular-image-converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
strum = { version = "0.24", features = ["derive"] }
crc = "2.1.0"
